export const LOCALIZACOES_STATUS = {
    STANDARD: '',
    LOADING: 'LOCALIZACOES_LOADING',
    ERROR: 'LOCALIZACOES_ERROR',
    SUCCESS: 'LOCALIZACOES_SUCCESS',
  };

export const LOCALIZACOES_ACTIONS = {
    STANDARD: '',
    PENDING: 'LOCALIZACOES_PENDING',
    FULFILLED: 'LOCALIZACOES_FULFILLED',
    REJECTED: 'LOCALIZACOES_REJECTED',
    };